version: "3.8"

x-build:
  &dockerfile-local-build
  context: .
  dockerfile: Dockerfile.local

services:
  db:
    image: postgres:10.1-alpine
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=httpmq_user
      - POSTGRES_PASSWORD=httpmq_password
      - POSTGRES_DB=httpmq_db
  app:
    container_name: app
    ports:
      - "8080:8080"
    build: *dockerfile-local-build
    volumes:
      - .:/app
